### ISSUE TITLE
画像のリンクがexample.comになっている。

### ISSUE THREAD

**Issue by tekapo** [jawordpressorg/wapuu#10]
画像のリンクがexample.comになってるのですが、それぞれの画像のベクター画像の置いてあるリポジトリなどのURLにしたいと思います。
@spicagraph さん、 @YasushiTakemoto さん、リンクがありましたらプルリクお願いします。

**Comment by YasushiTakemoto** [comment]
ありがとうございます。イラレなどのデータを置いたところのリンクをつけました。よろしくお願いします！

**Comment by tekapo** [comment]
@YasushiTakemoto さん、ありがとうございますー!

**Comment by tekapo** [comment]
Done.

**Comment by spicagraph** [comment]
確認が遅くなってすみません！
恐る恐るプルリクエスト送ってみたのですが合っているでしょうか…
不備があればすみません、どうぞ宜しくお願いします！
