### ISSUE TITLE
Wapuu API not maintained?

### ISSUE THREAD

**Issue by obstschale** [jawordpressorg/wapuu#111]
Hey there,

I have a custom made Wapuu and would like to add it to the list. This repo states:

> Give up Pull-Request to the [Wapuus JSON API](https://github.com/jawordpressorg/wapuu-api) project.

I did that https://github.com/jawordpressorg/wapuu-api/pull/17 but nothing is happing there? Is the API dead? Should I give PR to this repo instead?

**Comment by tekapo** [comment]
Sorry for being late.
I've just replied to your PR.
Thanks.
