### ISSUE TITLE
htmlの追加もお願いします。

### ISSUE THREAD

**Issue by tekapo** [jawordpressorg/wapuu#18]
@shield-9 さん、画像だけでなく、htmlの追加もお願いします。
参考: http://jawordpressorg.github.io/wapuu/faq.html

**Comment by shield-9** [comment]
了解です。これから作業します。

**Comment by shield-9** [comment]
#12 , #13 についてですが、GitHubのような場所で公開されていたものではなく各WordCampのウェブマスターさんからもらったものなので、作者不詳です。なので、とりあえず空欄のままPRを出します。

**Comment by tekapo** [comment]
マージしました。Thank you!
