### ISSUE TITLE
わぷー画像のプルリクについて

### ISSUE THREAD

**Issue by tekapo** [jawordpressorg/wapuu#2]
わぷーの画像をみなさんがフォークしてくださって、わぷーの派生版がたくさん産まれてるのですが、それをこの
https://github.com/jawordpressorg/wapuu/
にプルリクで集めましょうかねえ?
という話がFacebookであったんですが、プルリクはFacebookで宮内さんが書いてくれたように元のを上書きするイメージなのですです。

そこで、Githubページの機能を使って
https://github.com/jawordpressorg/wapuu/tree/gh-pages
をフォークしてもらって、ここにファイル追加などの形でプルリクしてもらいましょうか?ということをいま場当たり的にw思いついたんですが、どうでしょう?

でそのプルリクを、https://github.com/jawordpressorg/ の管理者がマージすると
http://jawordpressorg.github.io/wapuu/
に表示されるっていう感じです。

**Comment by naokomc** [comment]
はい、ページ機能を使ったサイトを立ち上げるという形が良いと思います。

**Comment by yat8823jp** [comment]
どういうふうになるのかイメージがちょっと沸かないので、実際にWordCamp Kansai2014のわぷーで試してみたいですね。

**Comment by nukaga** [comment]
今、いくつか派生わぷーがForkされて生まれていると思うのですが、それとは別に改めてアーカイブページ用にForkし直すという考え方であってますか？

**Comment by tekapo** [comment]
@yat8823jp さん、ぜひ試してみてください。
さっき思いついたんでw、試行錯誤しながらだと思いますが、いくらでも戻せるんでお気軽に!

**Comment by tekapo** [comment]
@nukaga さん、
そうですね。これまでに派生わぷーのフォーク元はもとのオリジナル画像なので、そのフォークからプルリクしてもオリジナル画像への変更をプルリクする形になってしまいますので。

**Comment by tekapo** [comment]
簡単に手順を(自分で試しつつw)書いてみますので、しばしお待ちを。

**Comment by nukaga** [comment]
@tekapoさん
了解しました！
ありがとうございます！

**Comment by tekapo** [comment]
わぷーのプルリクの送り方
1. Githubの「わぷー」のリポジトリをフォークします。すでにフォーク済み、clone済みの場合は「3」へ。
   - https://github.com/jawordpressorg/wapuu
2. フォークした _自分の_ リポジトリをローカルにcloneします
   - 例: $ git clone git@github.com:tekapo/wapuu.git 
3. フォーク、clone済みの場合は元のリポジトリに追従します
   - http://qiita.com/xtetsuji/items/555a1ef19ed21ee42873
4. gh-pagesブランチをcheckoutします。
   - $ git checkout gh-pages
5. wapuu-archiveフォルダー内に追加したい派生版わぷーの画像を入れてcommit、pushします。
6. 自分のGithubページからプルリクエストを送ります

**Comment by tekapo** [comment]
こんな感じですね。
すでにフォーク済みの場合は改めてフォークし直すんではなくて、元のリポジトリに追従、gh-pagesブランチをチェックアウトして追加、commit、pushでした。

**Comment by tekapo** [comment]
TODO:
- アーカイブ用のフォルダの名称の決定。とりあえず「wapuu-archive」としましたが、何がいいか?
- サイト全体のレイアウトやデザインはどうするか?
- トップページではプルリクの手順を記載?
- アーカイブ用ページの作成
- アーカイブ(一覧)掲載用の画像のサイズとフォーマットの決定
- わぷー画像掲載依頼用のプルリクメッセージのひな形

**Comment by naokomc** [comment]
@yat8823jp @nukaga みなさんには共有してなかったんですがイメージとしてはこんなかんじでした。 https://octodex.github.com こちらはオフィシャルのものだけ載せてるそうで、オープンソース的に作られてるわけではないですが…。

@tekapo 
- アーカイブ用フォルダ名: wapuu-archive 良いと思います。他にあるとすれば wapuu-offsprings、wapuu-variation とかかな？
- サイト全体: ocdodex 風にするか、もっと小さくしてずらっと並べるか…
- トップページではプルリクの手順を記載?: FAQ に書く + Fork me on GitHub リボン https://github.com/blog/273-github-ribbons でどうでしょう？

**Comment by tekapo** [comment]
@naokomc @nukaga @yat8823jp 
こんな感じでどうでしょー?
http://wbfukuoka.github.io/wapuu/
http://wbfukuoka.github.io/wapuu/wapuu-archive/

このリポジトリの中身はフツーのhtmlとcssなんでデザインとか文言とか適当に改善改良追加編集修正削除してプルリクを送ってもらえると助かりますm(__)m

**Comment by naokomc** [comment]
ありがとうございます！
細かい文言とかレイアウトはさておき、このサイトのトップは、オリジナルわぷーのダウンロードサイト的な感じにしますか？
（http://ja.wordpress.org/about-wp-ja/wapuu/ の GitHub Pages 版）

私がイメージしてたのはこのサイト自体は派生わぷーのショーケースという位置づけだったので、トップページにわぷーが並んでたほうがいいかなーと思っていたんですが、そもそものコンセプト認識がちょっと違ってたかもしれませんが…。

**Comment by tekapo** [comment]
@naokomc 
あー、なるほど!
わたしは
https://github.com/jawordpressorg/wapuu
イコール
http://jawordpressorg.github.io/wapuu/
と思い込んでたのでアーカイブは別ページかなとこれまた思い込んでました。

ので、トップページにわぷーを並べたほうが良さそうですね。
そうしましょう!

**Comment by tekapo** [comment]
@naokomc 
トップページに並べてみました。
http://wbfukuoka.github.io/wapuu/

**Comment by spicagraph** [comment]
WordCamp Kansai 2014炎わぷーをGithubに上げた角田です。
このわぷーアーカイブにもぜひ参加させていただきたのですが
「アーカイブ(一覧)掲載用の画像のサイズとフォーマットの決定」
これはもう決定されたでしょうか？
わぷーアーカイブはpngが並んでいたので、このサイズで透過pngを作成して入れる、あとはSVGでしょうか。
逆に、これ以外のものを入れてはいけませんか？aiデータが欲しいという声があって、今はaiデータも入れています。

**Comment by naokomc** [comment]
@tekapo ステキ！

@spicagraph サンプルページのサイズで行くならプルリクエストにはこのサイズの PNG 画像と派生わぷーアーカイブへのリンク、作者の ID とかを含めた修正を送るといいのかな？と思ったりしました。← @tekapo どうでしょう？

**Comment by tekapo** [comment]
@spicagraph @naokomc 

> サンプルページのサイズで行くならプルリクエストにはこのサイズの PNG 画像と派生わぷーアーカイブへのリンク、作者の ID とかを含めた修正を送るといいのかな？と思ったりしました。

はいー。いいと思います。ちょっと整理してこっちの元のやつにマージして手順も書き足すんで、しばしお待ちくださいませまし。

**Comment by tekapo** [comment]
@spicagraph 
以下で分かります? 
手順を随時修正しますので、すみませんが実験台wになっていただいて、分からないところ、詰まったところを教えていただけると助かります。
http://jawordpressorg.github.io/wapuu/faq.html
「わぷーアーカイブに追加するためのプルリクの送り方」

**Comment by spicagraph** [comment]
ターミナルが恐いものでsourcetreeを使っているのですが、すでに本家をクローンして内容を変更、コミットプッシュしたものに、元のリポジトリを追跡する方法がわからず…すごく初歩的なところで詰まっていますすみません…
そもそもsourcetreeにそういう機能があるのかもわからず、腹をくくってターミナルと仲良くすべきかと揺れています。
ちょっと間があいてしまいましたので取り急ぎご報告でした。

**Comment by tekapo** [comment]
@spicagraph 
SourceTreeでもできるはず。。。。でもぐぐっても方法が見つかりませんでした。。。
自分でも調べてみますね。
あと、ターミナルですが、恐るるにたらずですw
失敗しても簡単に戻せるのばバージョン管理システム(Git)のいいところなんで、気軽に試してみたらいいと思いますよー :-)

**Comment by hissy** [comment]
いま直接 @spicagraph さんに説明しましたが、SourceTreeの「設定」ボタンでリモートリポジトリを追加できますので、自分が管理している origin 以外に https://github.com/jawordpressorg/wapuu をリモートリポジトリに追加すれば、追加したリモートリポジトリの任意のブランチからローカルの任意のブランチに pull することが可能です。

**Comment by tekapo** [comment]
@hissy ありがとうございます!

**Comment by spicagraph** [comment]
WirdBench大阪の翻訳祭りのときにどうしても分からずヘルプ頂きました、ありがとうございます！！その前に勘違いしてWordCamp Kansaiの方にgh-pagesを作って一度削除してしまい、同じなまえのブランチをうまくプッシュできなかったので、また別名でやってみたいと思います。
お二人ともありがとうございます、遅くなってすみません…いましばしお時間ください（Gitこわすぎて落ち着いたときでないと出来なくて…

**Comment by hissy** [comment]
@spicagraph  コワーキングスペースとかで会うタイミングがあればサポートしますよ :beers:

**Comment by spicagraph** [comment]
hissyさんありがとうございますー！！Campの方でバタバタで放置になっていてすみません。
この間見ていただいてからどうしてもエラーで出来ないので、クローンしなおしたらできました！気がします！！
プルリクエスト送ってみたんですがどうでしょうか・・・tekapoさんよろしくお願いします。

**Comment by spicagraph** [comment]
マージありがとうございます！！
ちょっと時間がかかってしまったのは最初わたしが誤解して変な操作をしてしまったからで
それがなければ簡単に出来ました！ありがとうございましたー！！

**Comment by tekapo** [comment]
こちらこそ、ありがとうございます！
例としてダブって載せてたのも削除しました。

**Comment by spicagraph** [comment]
ほんとですね２人になった！
ずらっと並ぶの楽しみにしてます！

**Comment by YasushiTakemoto** [comment]
WordCampTokyo2014のわぷー制作した嵩本です。
僕も試行錯誤しながらやっているのですが、WordCampTokyo2014のわぷーをプルリクエスト送ってみたんですがどうでしょうか。
よろしくお願いします！
