### ISSUE TITLE
Missed Wapuu List

### ISSUE THREAD

**Issue by shield-9** [jawordpressorg/wapuu#50]
Here's the list of missed wapuus.
- [ ] [落花生わぷー](https://github.com/nekomimiTaicho/chiba-wapuu) (わぴー, 千葉)
- [ ] [雷門わぷー](https://tokyo.wordcamp.org/2011/files/2011/10/wapuu-tokyo-320.png) (WordCamp Tokyo 2011)
- [ ] いちごわぷー(栃木)
- [ ] うどんわぷー(香川)
- [ ] 和同弁知わぷー(奈良)
- [ ] ゴーヤわぷー(沖縄)
- [ ] サータアンダギーわぷー(沖縄)
- [ ] カステラわぷー(長崎)
- [ ] ちゃんぽんわぷー(長崎)
- [ ] えびすわぷー(大阪)
- [ ] 甲子園わぷー(大阪)
- [ ] ゆずわぷー(高知)
- [ ] lumberjack wapuu (WordCamp Maine 2015)
- [x] Kangawapuu (WordCamp Brisbane 2015)
- [ ] WordCamp Kansai 2015 wapuu
- [ ] 書道家わぷー (Camp Tokyo 2015)
- [ ] [Space wapuu](http://wapuu.amimoto-ami.com/) (DigitalCube Co. Ltd.)

**Comment by hinaloe** [comment]
Please also add below wapuu to the list :0
- [ ] WordCamp Kansai 2015 wapuu 
- [ ] 書道家わぷー (Camp Tokyo 2015)
- [ ] [Space wapuu](http://wapuu.amimoto-ami.com/) (DigitalCube Co. Ltd.)
