### ISSUE TITLE
Clarify licence of Wapuu images

### ISSUE THREAD

**Issue by leewillis77** [jawordpressorg/wapuu#69]
It would be helpful if there was a licence declaration - are _all_ images under GPL?

**Comment by tekapo** [comment]
@leewillis77 
Yes, all images are under GPL:
http://jawordpressorg.github.io/wapuu/faq_en.html

Do you mean the license declaration on the top page here?
http://jawordpressorg.github.io/wapuu/

**Comment by leewillis77** [comment]
Hi; 

I'd like to see a LICENSE.txt (or LICENSE.md) in the root of the repository. It would also be good to clarify the licence statement at the footer of the page:

Currently it says:
"Wapuu is licensed under GNU General Public License v2 or later. It's same as WordPress software. You can use in a plugin or theme. Wapuu's copyright is reserved by Kazuko Kaneuchi."

It's not obvious (to me) that this covers all of the variations. If that can be clarified - that would be great!

Thanks for taking the time to reply :)

**Comment by tekapo** [comment]
You are right. I've added LICENSE.txt. to the root of the repository.
Thank you for your advice, @leewillis77!
